apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acm-route53-operator
rules:
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
